create table if not exists public.building (
  building_id bigint generated by default as identity primary key,
  building_name text not null unique,
  floor_total integer not null check (floor_total > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  user_id text primary key,
  user_name text not null,
  jurusan text not null default '',
  angkatan integer not null check (angkatan >= 1900),
  created_at timestamptz not null default now()
);

create table if not exists public.ruangan (
  room_id text primary key,
  building_id bigint not null references public.building(building_id) on update cascade on delete restrict,
  floor integer not null check (floor > 0),
  room_number integer not null,
  foto text,
  kapasitas integer not null check (kapasitas > 0),
  deskripsi text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.schedule (
  schedule_id bigint generated by default as identity primary key,
  room_id text not null references public.ruangan(room_id) on update cascade on delete cascade,
  user_id text not null references public.users(user_id) on update cascade on delete restrict,
  schedule_name text not null,
  tanggal_dimulai timestamptz not null,
  tanggal_selesai timestamptz not null,
  created_at timestamptz not null default now(),
  constraint schedule_time_check check (tanggal_selesai > tanggal_dimulai)
);

create table if not exists public.peminjaman (
  peminjaman_id bigint generated by default as identity primary key,
  room_id text not null references public.ruangan(room_id) on update cascade on delete restrict,
  user_id text not null references public.users(user_id) on update cascade on delete restrict,
  nama_kegiatan text not null,
  tanggal_dimulai timestamptz not null,
  tanggal_selesai timestamptz not null,
  deskripsi text not null default '',
  jumlah_peserta integer not null check (jumlah_peserta > 0),
  dokumen text,
  status text not null default 'menunggu' check (status in ('menunggu', 'disetujui', 'ditolak')),
  created_at timestamptz not null default now(),
  constraint peminjaman_time_check check (tanggal_selesai > tanggal_dimulai)
);

create index if not exists idx_schedule_room_tanggal on public.schedule(room_id, tanggal_dimulai);
create index if not exists idx_peminjaman_room_tanggal on public.peminjaman(room_id, tanggal_dimulai);

alter table public.building enable row level security;
alter table public.users enable row level security;
alter table public.ruangan enable row level security;
alter table public.schedule enable row level security;
alter table public.peminjaman enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'building' and policyname = 'Public read building') then
    create policy "Public read building" on public.building for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'Public read users') then
    create policy "Public read users" on public.users for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'ruangan' and policyname = 'Public read ruangan') then
    create policy "Public read ruangan" on public.ruangan for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'schedule' and policyname = 'Public read schedule') then
    create policy "Public read schedule" on public.schedule for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'peminjaman' and policyname = 'Public read peminjaman') then
    create policy "Public read peminjaman" on public.peminjaman for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'peminjaman' and policyname = 'Public insert peminjaman') then
    create policy "Public insert peminjaman" on public.peminjaman for insert to anon, authenticated with check (true);
  end if;
end
$$;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('foto', 'foto', true)
on conflict (id) do update set public = excluded.public;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public read foto bucket') then
    create policy "Public read foto bucket" on storage.objects for select to anon, authenticated using (bucket_id = 'foto');
  end if;
end
$$;
